### PR TITLE
feat(config): orientation

### PR DESCRIPTION
**Pull request by DSergiu**

### CODE REVIEW

**Comment by CAMOBAP** [comment]
@DSergiu is there some `AUTO` orientation? For example, what happens if the user rotates the device to landscape with Captcha that configured with `orientation=portrait`?

**Review by CAMOBAP — COMMENTED** [review]
LGTM except open question https://github.com/hCaptcha/hcaptcha-android-sdk/pull/103#issuecomment-1490781422

**Review by e271828- — APPROVED** [review]

**Comment by DSergiu** [comment]
> @DSergiu is there some `AUTO` orientation? For example, what happens if the user rotates the device to landscape with Captcha that configured with `orientation=portrait`?

There is currently no `AUTO` support. @CAMOBAP

**Review by CAMOBAP — APPROVED** [review]

**Comment by CAMOBAP** [comment]
> > @DSergiu is there some `AUTO` orientation? For example, what happens if the user rotates the device to landscape with Captcha that configured with `orientation=portrait`?
> 
> There is currently no `AUTO` support. @CAMOBAP

If `portrait`/`landscape` will correctly handle rotation there is probably no need to have one

**Comment by CAMOBAP** [comment]
Similar PR for iOS https://github.com/hCaptcha/HCaptcha-ios-sdk/pull/111

**Pull request merged**
